### PR TITLE
Update eosio.system-regproducer-rc.md

### PR DESCRIPTION
**Pull request by jafri**
Rationale: this is to prevent non-disclosure of revenue sharing agreements, not just equity ownership. This remains in the spirit of this clause and should not be a controversial update.

Proposed by Rick Schlesinger from EOS New York.

### CODE REVIEW

**Comment by thomasbcox** [comment]
Let's please keep this open until we've gotten a sense of whether it will be disruptive to the current group consensus to make this change. 

I don't expect it will, but one never knows.

**Comment by robrigo** [comment]
I support this clarification of the block producer terms to prevent profit sharing arrangements from going undisclosed.

**Comment by GunnisonCap** [comment]
Clearly worded, I support this as a logical amendment that closes a potential loophole in the intended spirit of this.  My view is this should be made and committed immediately.

**Comment by nsjames** [comment]
This looks good to me. Let's get some more people chiming in here though as this is one of the most contended articles.

**Comment by EOSMediterranean** [comment]
Looks good to us!

**Comment by DMTrueBlock** [comment]
This Github repository is NOT the place to make ANY more changes to Block Producer agreements, the Constitution, or any other document. Any changes going forward need to follow a proposal, voting, ratification and adoption process by the Block Producers themselves AFTER the mainnet launch. I am a mere repository owner but will not consent to any further changes unless they follow that same process now; that, of course, is logistically impossible.

**Comment by thomasbcox** [comment]
Sounds like, given the timing, this cannot be added pre-launch. Let's keep this open until a better location is discovered for queueing proposals for referenda. 

I'm sure if voters care enough about this, they'll press for voluntary disclosure, particularly now that the topic has been broached.

**Comment by eny-rs** [comment]
Agree with @DMTrueBlock and would like to rescind the suggestion until we have a functioning chain so that the community can vote on this particular adjustment.

**Comment by eosBlockSmith** [comment]
BlockSmith supports this change BEFORE launch.  This is fundamental to keeping corruption and collusion out.  We need this kind of rule now, or we may never get it after launch.  It's important to set out on the right foot.

We would ask, plead, and beg the community to adopt this change immediately for the health and welfare of EOS and all those operating in it.

**Comment by nsjames** [comment]
The general consensus here is that no one has any issue with this addition, but most also don't have an issue with it happening afterwards on chain and because we are so close to launch I'm going to close this pull without merging but not lock the thread so that it can keep getting comments in a public fashion which we can use as future support.

**Comment by bt-cryptomancer** [comment]
BuildTeam BP candidate also supports making this change at the earliest practical opportunity, before or after launch.  Transparency is important and this is a good way to strengthen the original clause.

**Comment by summerskin** [comment]
joining in to voice my support for this issue.

**Comment by GMory** [comment]
Fully support this, and if at all possible would love to see it included pre-launch.

**Comment by DenisCarriere** [comment]
Agree, raise the flag, address early on.

I don't think we should change it pre-launch (although we fully support the change 100%)

**Comment by generEOS** [comment]
GenerEOS support this change preferable before the launch!

**Comment by hydrosloth** [comment]
I support this change, also preferably before launch

**Comment by eosBlockSmith** [comment]
I'm sad to see this not get merged @nsjames ... I don't agree that there is not sufficient consensus to get it merged.  Doing it after launch may mean never doing it, and it's a clear loophole in the intention of the rule.  If I can, instead of selling an ownership share, simply give my profit to someone, I've circumvented the rule.  I see no reason not to add it, and am disappointing to see it put off.

**Comment by visualbasic6** [comment]
@eosBlockSmith @nsjames not only is this already certified by sufficient consensus but i bet even more community feedback in favor of this is on its way. time to merge!

**Comment by null-nv** [comment]
Highly supported, preferably after launch if there is minimal impact.

**Comment by eosBlockSmith** [comment]
@null-nv  please realize we cannot simply merge this after launch, it must be voted in by referendum, a system for which does not even exist yet.  Leaving it out of launch has a very real possibility of keeping it out forever.

**Comment by samsapoznick** [comment]
I agree that this pull would represent an incremental improvement in the BP ownership governance language. However, I am with David Moss in calling for this NOT to be merged prior to launch. There is the beginning of western/english-language community consensus appearing for this change, but I do not see broad Chinese and Korean-language community consensus added here. (In the form of Github comments.)

To merge without substantial additional consensus would be, I think, a mistaken use of power, allowed to slide by the fact the the github repo *happens* to be in the control of largely English-language persons. The symbolic impact and potential damage of changing wording that is explicitly-laid-out in the [EOS Go Forums governance announcement](https://forums.eosgo.io/discussion/1109/governance-announcement/) without strong consent from most or all of the BPCs listed could be as bad, or worse, in long-term impact, than leaving the wording as it is in order to respect the good consensus already achieved and needed for a smooth and uncontested launch.

If broad Chinese and Korean assent and consensus (resembling that shown in the EOSGo forums post) can be achieved in the time remaining before launch, then I would support the change. 
If a high level of CN/KR consensus cannot be achieved, I do not support this or any other discretionary change to governance language before launch.

**Comment by eosBlockSmith** [comment]
@samsapoznick Well said.  I understand your position and I agree with you.  I have reached out to in the hopes we can get some of our Mandarin speaking family to present their opinions.

**Comment by visualbasic6** [comment]
@samsapoznick at this point it is the preexisting responsibility of china and korea to be where the action is 24/7. that said, they're now already on notice:

korea: https://i.imgur.com/K8gLSOL.png
china: https://i.imgur.com/RpjBqz6.png

**Comment by nsjames** [comment]
If this reaches 36+ BPs vying for it to be included pre-launch with 50% of them being from non-english speaking countries I'll reopen and merge this.

If your BP name isn't clearly states in your GitHub name please provide it along with your consent.

**Comment by indend007** [comment]
I'm sharing this with Korean BP community.

**Comment by visualbasic6** [comment]
@nsjames bps have not been voted in yet. does that not make this a community vote? any _genuine_ cultural divide of significance on this matter of decentralization seems very unlikely.

**Comment by EOSBIXIN** [comment]
EOSBIXIN support this proposal.

**Comment by DutchEOS** [comment]
This is confusing. In my mind we were already wondering to what extent an equity share was conflicting with Article 4 (No vote buying). After sticking a vote buying price list on your BP website, a revenue share approach is the next most logical way to construct vote buying and therefore IMO already a clear violation of Article 4. But perhaps most importantly by describing in detail what constructs of vote buying are allowed / don't need to be disclosed  (up to a certain %) we are weakening Article 4. [DutchEOS](http://dutcheos.io) would therefore much rather see that the BPA (or better yet Constitution) states explicitly that ["No person or entity shall own (directly or indirectly) any stake in more than one BP." ](https://forums.eosgo.io/discussion/1025/eosreal-revised-version-of-eos-block-producer-agreement-stage-1-may-25-2018#latest)

**Comment by jorfermo** [comment]
EOSMetal supports this change. Preferably before the launch.

**Comment by damianbyeon** [comment]
AcroEOS support this proposal.

**Comment by HassanAmad** [comment]
I fully support doing this BEFORE LAUNCH. This should be worked out before corruption can take place. This will look bad on any block producer/ dapp developer who does not support before launch. Delaying 1 week is not a huge deal and it will be better long term for the value of the project.

**Comment by ramtej** [comment]
EOS Germany - we support the proposal.

**Comment by HassanAmad** [comment]
@samsapoznick The contract is written in English, so i see no problem here. It involves a fundamental principle of decentralization that every person in the blockchain space would agree with (unless they desire centralization). It should be resolved immediately, and if anyone still objects we can vote to remove it post launch. The burden of the vote should be on those that wish to remove it, given that the proposal prevents corruption and centralization. So on that note, your logic cuts both ways here. If it was added by the b.one team before the freeze, then this would not have been an issue and everyone would have went with it. Given the importance of such a provision for network health, there is no reason to launch quickly with such important things left undone.

**Comment by blujimbo** [comment]
I vote for merge now. It's important. 

This:
> The burden of the vote should be on those that wish to remove it, given that the proposal prevents corruption and centralization.  (@HassanAmad)

**Comment by kesar** [comment]
I love the idea ❤️ , but I will vote to add it **after** launch with proper voting system in place and elected BPs. 🗳

**Comment by var-let-const** [comment]
Team Eossey support this proposal as well 👍

**Comment by EOSYS-io** [comment]
EOSYS supports this as well

**Comment by Hashbit-Technologies** [comment]
Hashbit supports this. Preferably included before launch. Like @HassanAmad said, the potential consequences of it *never* being voted in, far outweigh the consequences of it being voted out.

**Pull request closed without merging**
