### PR TITLE
rolls back change to article IX

### PR DESCRIPTION
**Pull request by thomasbcox**
rolls back the change made around May 30, where the default forum was switched from ECAF to ICC, the International Chamber of Commerce's arbitration forum

### CODE REVIEW

**Comment by thomasbcox** [comment]
Please do not merge this PR until it's been thoroughly discussed

**Comment by DenisCarriere** [comment]
Added checksums & ipfs for both `eosio.system` & `eosio.token` ABI

**ipfs.txt**
```
added QmdiEnPy2ZprjGe3vfxikg9fNaJR77bbMcVMBwWh64ajCm eosio.system.abi
added QmTgfMfMw2zQgtkeSu7iJfaVcWbmU8werBjYuf6iVseFXL eosio.token.abi
```

**checksums.txt**
```
b15749b745ccbbce4a2ef9e6139c84cad131ddd2582713b1f545b7b489e8f394  ./eosio.system/eosio.system.abi
804533704bfa098d2399808a806cb37cc4256da3ce9b0d9a777b3ab21c4fe778  ./eosio.token/eosio.token.abi
```

**Comment by kesar** [comment]
I think the way that we are merging and adding code could improve a lot.

- Who decided to add checksums, IPFS & scripts? 
- Who support this change? Do we need 3 votes to change the constitution?

I am aware that this get more votes over telegram chats, but I think it should be explicit somewhere here, otherwise those votes will get lost. Even if I like this PR, I think the work around the acceptance is poor.

I guess IPFS & extra scripts are for bios boot. I don't this that there is an agreement between BPs to use that. This could end up with every BP boot adding more and more files here.

I also think that if someone adds code, it should request a review from somebody else. It didn't happen.

**Comment by DenisCarriere** [comment]
@kesar I added `ipfs` and `checksums` to make sure we have this file already hosted and someone can grab it easily.

However I do agree, we can keep this github repo "lean" and remove any extra scripts or extra supporting files, only stick with what's needed.

**Comment by kesar** [comment]
yes, just to avoid confusion, I think content of PR is great, and that you are all doing your best ❤️  

Just wanted to point some stuff that we could improve in the future 👍

**Comment by DenisCarriere** [comment]
@kesar agreed, that last commit should of been in it's own PR (or discussed prior to merging).

👍

**Pull request merged**
